### ISSUE TITLE
Insecure user matching only based on identifier

### ISSUE THREAD

**Issue by pawel-kow** [bembelimen/Joomla-ID4Me-Login#8]
https://github.com/bembelimen/Joomla-ID4Me-Login/blob/6cbbd57f07e5f4a86fb5ac8bc39f19de0b78f0a3/src/plugins/system/id4me/id4me.php#L257

Reading the code I see that the identifier the user input into the login form is being matched against the database. There is no verification whether the authorization that was returned refers really to the same user.
According to OpenID Connect that shall be done with the pair `iss` and `sub` claims of an IDToken.
The values are available in the `AuthorizationTokens` object  `getIdTokenDecoded()->getIss()` and `getIdTokenDecoded()->getSub()` accordingly.
Very common way of doing that is encoding both values in one field like URL `iss#sub` (iss is in fact URL without query string or fragment part).

**Comment by bembelimen** [comment]
Matching now based on ISS + SUB, too.
