### ISSUE TITLE
Client registered anew on each login & wrong client name used

### ISSUE THREAD

**Issue by pawel-kow** [bembelimen/Joomla-ID4Me-Login#9]
https://github.com/bembelimen/Joomla-ID4Me-Login/blob/5d5f70ef6acb4d2cb23e1c25aefc019c96268ed2/src/plugins/system/id4me/id4me.php#L212

I noticed 2 things (mentioned in the Email from 28/10):
1) client is not saved after registration and is re-registered each time. That may work, but it is very ineffective and may even lead to website ban by the IdP. The example code has a simple file-based solution, I believe in Joomla! should you save it in the database somewhere.
2) the 2nd parameter of $this->ID4MeHandler()->register() is the page name (probably something you have in the global configuration of a website). I have adapted it as well in the example.

**Comment by bembelimen** [comment]
Thx,
see https://github.com/bembelimen/Joomla-ID4Me-Login/commit/d2f10d7b984b8b12683adcf2a57293b0958d08da
